import { Item, User, PickupRequest, RecyclingBatch, Order, AnalyticsData, Offer } from '../types';

export const initialUsers: User[] = [
  {
    id: 'usr_admin_1',
    name: 'Sanyam (Founder & Admin)',
    email: 'sanyam0902@gmail.com',
    password: 'Gamma@12',
    phone: '8708288911',
    gender: 'male',
    role: 'admin',
    isOnline: true,
    isFounder: true,
    adminPermissions: {
      canViewInsights: true,
      canViewOrders: true,
      canViewPasswords: true,
      canManageCatalog: true,
      canManageIndustry: true,
      isFounder: true
    },
    rating: 5.0,
    ratingCount: 1,
    walletBalance: 0,
    createdAt: '2026-07-01'
  },
  {
    id: 'usr_customer_1',
    name: 'Sanyam (Consumer & Seller)',
    email: 'sanyam0902@gmail.com',
    password: 'User@123',
    phone: '8708288911',
    gender: 'male',
    role: 'customer',
    isOnline: false,
    rating: 5.0,
    ratingCount: 2,
    walletBalance: 0,
    address: {
      id: 'addr_1',
      userId: 'usr_customer_1',
      line1: 'C-14, Hauz Khas Enclave',
      city: 'New Delhi',
      state: 'Delhi NCR',
      pincode: '110016',
      isDefault: true
    },
    createdAt: '2026-07-10'
  },
  {
    id: 'usr_industry_1',
    name: 'Delhi NCR EcoTextile Recycling Hub',
    email: 'sanyam0902@gmail.com',
    password: 'Ind@12345',
    phone: '8708288911',
    gender: 'other',
    role: 'industry_partner',
    businessName: 'VastraChakra EcoMills Delhi NCR',
    gstNumber: '07AAACV0902F1Z8',
    isVerified: true,
    isOnline: false,
    rating: 5.0,
    ratingCount: 1,
    walletBalance: 0,
    createdAt: '2026-07-15'
  },

  {
    "id": "CUST0001",
    "name": "Arjun Sharma",
    "email": "customer001@example.com",
    "password": "Demo@1000",
    "phone": "9000000001",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0001",
      "userId": "CUST0001",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0002",
    "name": "Rahul Mehta",
    "email": "customer002@example.com",
    "password": "Demo@1001",
    "phone": "9000000002",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0002",
      "userId": "CUST0002",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0003",
    "name": "Kunal Gupta",
    "email": "customer003@example.com",
    "password": "Demo@1002",
    "phone": "9000000003",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0003",
      "userId": "CUST0003",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0004",
    "name": "Arjun Khanna",
    "email": "customer004@example.com",
    "password": "Demo@1003",
    "phone": "9000000004",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0004",
      "userId": "CUST0004",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0005",
    "name": "Shreya Verma",
    "email": "customer005@example.com",
    "password": "Demo@1004",
    "phone": "9000000005",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0005",
      "userId": "CUST0005",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0006",
    "name": "Tanya Malhotra",
    "email": "customer006@example.com",
    "password": "Demo@1005",
    "phone": "9000000006",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0006",
      "userId": "CUST0006",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0007",
    "name": "Vivaan Sharma",
    "email": "customer007@example.com",
    "password": "Demo@1006",
    "phone": "9000000007",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0007",
      "userId": "CUST0007",
      "line1": "Sector 14, Ghaziabad",
      "city": "Ghaziabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0008",
    "name": "Aditya Mehta",
    "email": "customer008@example.com",
    "password": "Demo@1007",
    "phone": "9000000008",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0008",
      "userId": "CUST0008",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0009",
    "name": "Kunal Bansal",
    "email": "customer009@example.com",
    "password": "Demo@1008",
    "phone": "9000000009",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0009",
      "userId": "CUST0009",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0010",
    "name": "Simran Sharma",
    "email": "customer010@example.com",
    "password": "Demo@1009",
    "phone": "9000000010",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0010",
      "userId": "CUST0010",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0011",
    "name": "Shreya Mehta",
    "email": "customer011@example.com",
    "password": "Demo@1010",
    "phone": "9000000011",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0011",
      "userId": "CUST0011",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0012",
    "name": "Shreya Malhotra",
    "email": "customer012@example.com",
    "password": "Demo@1011",
    "phone": "9000000012",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0012",
      "userId": "CUST0012",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0013",
    "name": "Kunal Jain",
    "email": "customer013@example.com",
    "password": "Demo@1012",
    "phone": "9000000013",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0013",
      "userId": "CUST0013",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0014",
    "name": "Tanya Singh",
    "email": "customer014@example.com",
    "password": "Demo@1013",
    "phone": "9000000014",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0014",
      "userId": "CUST0014",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0015",
    "name": "Aarav Sethi",
    "email": "customer015@example.com",
    "password": "Demo@1014",
    "phone": "9000000015",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0015",
      "userId": "CUST0015",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0016",
    "name": "Rohan Chopra",
    "email": "customer016@example.com",
    "password": "Demo@1015",
    "phone": "9000000016",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0016",
      "userId": "CUST0016",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0017",
    "name": "Meera Kapoor",
    "email": "customer017@example.com",
    "password": "Demo@1016",
    "phone": "9000000017",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0017",
      "userId": "CUST0017",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0018",
    "name": "Rahul Gupta",
    "email": "customer018@example.com",
    "password": "Demo@1017",
    "phone": "9000000018",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0018",
      "userId": "CUST0018",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0019",
    "name": "Yash Sethi",
    "email": "customer019@example.com",
    "password": "Demo@1018",
    "phone": "9000000019",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0019",
      "userId": "CUST0019",
      "line1": "Sector 14, Greater Noida",
      "city": "Greater Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0020",
    "name": "Aanya Verma",
    "email": "customer020@example.com",
    "password": "Demo@1019",
    "phone": "9000000020",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0020",
      "userId": "CUST0020",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0021",
    "name": "Aditya Malhotra",
    "email": "customer021@example.com",
    "password": "Demo@1020",
    "phone": "9000000021",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0021",
      "userId": "CUST0021",
      "line1": "Sector 14, Greater Noida",
      "city": "Greater Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0022",
    "name": "Arjun Kapoor",
    "email": "customer022@example.com",
    "password": "Demo@1021",
    "phone": "9000000022",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0022",
      "userId": "CUST0022",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0023",
    "name": "Ishita Agarwal",
    "email": "customer023@example.com",
    "password": "Demo@1022",
    "phone": "9000000023",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0023",
      "userId": "CUST0023",
      "line1": "Sector 14, East Delhi",
      "city": "East Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0024",
    "name": "Rahul Sethi",
    "email": "customer024@example.com",
    "password": "Demo@1023",
    "phone": "9000000024",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0024",
      "userId": "CUST0024",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0025",
    "name": "Vivaan Chopra",
    "email": "customer025@example.com",
    "password": "Demo@1024",
    "phone": "9000000025",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0025",
      "userId": "CUST0025",
      "line1": "Sector 14, Faridabad",
      "city": "Faridabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0026",
    "name": "Nisha Bansal",
    "email": "customer026@example.com",
    "password": "Demo@1025",
    "phone": "9000000026",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0026",
      "userId": "CUST0026",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0027",
    "name": "Arjun Mishra",
    "email": "customer027@example.com",
    "password": "Demo@1026",
    "phone": "9000000027",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0027",
      "userId": "CUST0027",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0028",
    "name": "Diya Verma",
    "email": "customer028@example.com",
    "password": "Demo@1027",
    "phone": "9000000028",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0028",
      "userId": "CUST0028",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0029",
    "name": "Shreya Singh",
    "email": "customer029@example.com",
    "password": "Demo@1028",
    "phone": "9000000029",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0029",
      "userId": "CUST0029",
      "line1": "Sector 14, Greater Noida",
      "city": "Greater Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0030",
    "name": "Simran Mishra",
    "email": "customer030@example.com",
    "password": "Demo@1029",
    "phone": "9000000030",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0030",
      "userId": "CUST0030",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0031",
    "name": "Ishita Agarwal",
    "email": "customer031@example.com",
    "password": "Demo@1030",
    "phone": "9000000031",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0031",
      "userId": "CUST0031",
      "line1": "Sector 14, Greater Noida",
      "city": "Greater Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0032",
    "name": "Yash Chopra",
    "email": "customer032@example.com",
    "password": "Demo@1031",
    "phone": "9000000032",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0032",
      "userId": "CUST0032",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0033",
    "name": "Aditya Sharma",
    "email": "customer033@example.com",
    "password": "Demo@1032",
    "phone": "9000000033",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0033",
      "userId": "CUST0033",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0034",
    "name": "Kunal Sethi",
    "email": "customer034@example.com",
    "password": "Demo@1033",
    "phone": "9000000034",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0034",
      "userId": "CUST0034",
      "line1": "Sector 14, Bahadurgarh",
      "city": "Bahadurgarh",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0035",
    "name": "Ananya Verma",
    "email": "customer035@example.com",
    "password": "Demo@1034",
    "phone": "9000000035",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0035",
      "userId": "CUST0035",
      "line1": "Sector 14, East Delhi",
      "city": "East Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0036",
    "name": "Kunal Arora",
    "email": "customer036@example.com",
    "password": "Demo@1035",
    "phone": "9000000036",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0036",
      "userId": "CUST0036",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0037",
    "name": "Arjun Malhotra",
    "email": "customer037@example.com",
    "password": "Demo@1036",
    "phone": "9000000037",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0037",
      "userId": "CUST0037",
      "line1": "Sector 14, Greater Noida",
      "city": "Greater Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0038",
    "name": "Rahul Jain",
    "email": "customer038@example.com",
    "password": "Demo@1037",
    "phone": "9000000038",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0038",
      "userId": "CUST0038",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0039",
    "name": "Ishita Gupta",
    "email": "customer039@example.com",
    "password": "Demo@1038",
    "phone": "9000000039",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0039",
      "userId": "CUST0039",
      "line1": "Sector 14, Ghaziabad",
      "city": "Ghaziabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0040",
    "name": "Ishita Kapoor",
    "email": "customer040@example.com",
    "password": "Demo@1039",
    "phone": "9000000040",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0040",
      "userId": "CUST0040",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0041",
    "name": "Yash Khanna",
    "email": "customer041@example.com",
    "password": "Demo@1040",
    "phone": "9000000041",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0041",
      "userId": "CUST0041",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0042",
    "name": "Rahul Chopra",
    "email": "customer042@example.com",
    "password": "Demo@1041",
    "phone": "9000000042",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0042",
      "userId": "CUST0042",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0043",
    "name": "Aditya Agarwal",
    "email": "customer043@example.com",
    "password": "Demo@1042",
    "phone": "9000000043",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0043",
      "userId": "CUST0043",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0044",
    "name": "Rohan Bansal",
    "email": "customer044@example.com",
    "password": "Demo@1043",
    "phone": "9000000044",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0044",
      "userId": "CUST0044",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0045",
    "name": "Kunal Gupta",
    "email": "customer045@example.com",
    "password": "Demo@1044",
    "phone": "9000000045",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0045",
      "userId": "CUST0045",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0046",
    "name": "Nisha Malhotra",
    "email": "customer046@example.com",
    "password": "Demo@1045",
    "phone": "9000000046",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0046",
      "userId": "CUST0046",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0047",
    "name": "Rahul Mishra",
    "email": "customer047@example.com",
    "password": "Demo@1046",
    "phone": "9000000047",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0047",
      "userId": "CUST0047",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0048",
    "name": "Shreya Mehta",
    "email": "customer048@example.com",
    "password": "Demo@1047",
    "phone": "9000000048",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0048",
      "userId": "CUST0048",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0049",
    "name": "Aanya Arora",
    "email": "customer049@example.com",
    "password": "Demo@1048",
    "phone": "9000000049",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0049",
      "userId": "CUST0049",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0050",
    "name": "Vivaan Mehta",
    "email": "customer050@example.com",
    "password": "Demo@1049",
    "phone": "9000000050",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0050",
      "userId": "CUST0050",
      "line1": "Sector 14, East Delhi",
      "city": "East Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0051",
    "name": "Vivaan Sethi",
    "email": "customer051@example.com",
    "password": "Demo@1050",
    "phone": "9000000051",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0051",
      "userId": "CUST0051",
      "line1": "Sector 14, East Delhi",
      "city": "East Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0052",
    "name": "Aanya Malhotra",
    "email": "customer052@example.com",
    "password": "Demo@1051",
    "phone": "9000000052",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0052",
      "userId": "CUST0052",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0053",
    "name": "Rahul Verma",
    "email": "customer053@example.com",
    "password": "Demo@1052",
    "phone": "9000000053",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0053",
      "userId": "CUST0053",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0054",
    "name": "Yash Mishra",
    "email": "customer054@example.com",
    "password": "Demo@1053",
    "phone": "9000000054",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0054",
      "userId": "CUST0054",
      "line1": "Sector 14, Faridabad",
      "city": "Faridabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0055",
    "name": "Tanya Mishra",
    "email": "customer055@example.com",
    "password": "Demo@1054",
    "phone": "9000000055",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0055",
      "userId": "CUST0055",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0056",
    "name": "Aanya Mehta",
    "email": "customer056@example.com",
    "password": "Demo@1055",
    "phone": "9000000056",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0056",
      "userId": "CUST0056",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0057",
    "name": "Kavya Malhotra",
    "email": "customer057@example.com",
    "password": "Demo@1056",
    "phone": "9000000057",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0057",
      "userId": "CUST0057",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0058",
    "name": "Nisha Gupta",
    "email": "customer058@example.com",
    "password": "Demo@1057",
    "phone": "9000000058",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0058",
      "userId": "CUST0058",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0059",
    "name": "Rahul Gupta",
    "email": "customer059@example.com",
    "password": "Demo@1058",
    "phone": "9000000059",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0059",
      "userId": "CUST0059",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0060",
    "name": "Kunal Chopra",
    "email": "customer060@example.com",
    "password": "Demo@1059",
    "phone": "9000000060",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0060",
      "userId": "CUST0060",
      "line1": "Sector 14, East Delhi",
      "city": "East Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0061",
    "name": "Shreya Bansal",
    "email": "customer061@example.com",
    "password": "Demo@1060",
    "phone": "9000000061",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0061",
      "userId": "CUST0061",
      "line1": "Sector 14, Bahadurgarh",
      "city": "Bahadurgarh",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0062",
    "name": "Rahul Chopra",
    "email": "customer062@example.com",
    "password": "Demo@1061",
    "phone": "9000000062",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0062",
      "userId": "CUST0062",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0063",
    "name": "Tanya Malhotra",
    "email": "customer063@example.com",
    "password": "Demo@1062",
    "phone": "9000000063",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0063",
      "userId": "CUST0063",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0064",
    "name": "Tanya Malhotra",
    "email": "customer064@example.com",
    "password": "Demo@1063",
    "phone": "9000000064",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0064",
      "userId": "CUST0064",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0065",
    "name": "Ishita Mehta",
    "email": "customer065@example.com",
    "password": "Demo@1064",
    "phone": "9000000065",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0065",
      "userId": "CUST0065",
      "line1": "Sector 14, Greater Noida",
      "city": "Greater Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0066",
    "name": "Kabir Bansal",
    "email": "customer066@example.com",
    "password": "Demo@1065",
    "phone": "9000000066",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0066",
      "userId": "CUST0066",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0067",
    "name": "Kavya Verma",
    "email": "customer067@example.com",
    "password": "Demo@1066",
    "phone": "9000000067",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0067",
      "userId": "CUST0067",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0068",
    "name": "Vivaan Arora",
    "email": "customer068@example.com",
    "password": "Demo@1067",
    "phone": "9000000068",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0068",
      "userId": "CUST0068",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0069",
    "name": "Arjun Gupta",
    "email": "customer069@example.com",
    "password": "Demo@1068",
    "phone": "9000000069",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0069",
      "userId": "CUST0069",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0070",
    "name": "Rohan Sethi",
    "email": "customer070@example.com",
    "password": "Demo@1069",
    "phone": "9000000070",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0070",
      "userId": "CUST0070",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0071",
    "name": "Meera Agarwal",
    "email": "customer071@example.com",
    "password": "Demo@1070",
    "phone": "9000000071",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0071",
      "userId": "CUST0071",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0072",
    "name": "Aditya Malhotra",
    "email": "customer072@example.com",
    "password": "Demo@1071",
    "phone": "9000000072",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0072",
      "userId": "CUST0072",
      "line1": "Sector 14, Faridabad",
      "city": "Faridabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0073",
    "name": "Diya Agarwal",
    "email": "customer073@example.com",
    "password": "Demo@1072",
    "phone": "9000000073",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0073",
      "userId": "CUST0073",
      "line1": "Sector 14, Ghaziabad",
      "city": "Ghaziabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0074",
    "name": "Nisha Bansal",
    "email": "customer074@example.com",
    "password": "Demo@1073",
    "phone": "9000000074",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0074",
      "userId": "CUST0074",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0075",
    "name": "Rahul Bansal",
    "email": "customer075@example.com",
    "password": "Demo@1074",
    "phone": "9000000075",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0075",
      "userId": "CUST0075",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0076",
    "name": "Aarav Khanna",
    "email": "customer076@example.com",
    "password": "Demo@1075",
    "phone": "9000000076",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0076",
      "userId": "CUST0076",
      "line1": "Sector 14, East Delhi",
      "city": "East Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0077",
    "name": "Arjun Khanna",
    "email": "customer077@example.com",
    "password": "Demo@1076",
    "phone": "9000000077",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0077",
      "userId": "CUST0077",
      "line1": "Sector 14, Faridabad",
      "city": "Faridabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0078",
    "name": "Shreya Sethi",
    "email": "customer078@example.com",
    "password": "Demo@1077",
    "phone": "9000000078",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0078",
      "userId": "CUST0078",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0079",
    "name": "Rahul Sethi",
    "email": "customer079@example.com",
    "password": "Demo@1078",
    "phone": "9000000079",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0079",
      "userId": "CUST0079",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0080",
    "name": "Aanya Verma",
    "email": "customer080@example.com",
    "password": "Demo@1079",
    "phone": "9000000080",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0080",
      "userId": "CUST0080",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0081",
    "name": "Ananya Malhotra",
    "email": "customer081@example.com",
    "password": "Demo@1080",
    "phone": "9000000081",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0081",
      "userId": "CUST0081",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0082",
    "name": "Rohan Jain",
    "email": "customer082@example.com",
    "password": "Demo@1081",
    "phone": "9000000082",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0082",
      "userId": "CUST0082",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0083",
    "name": "Aarav Chopra",
    "email": "customer083@example.com",
    "password": "Demo@1082",
    "phone": "9000000083",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0083",
      "userId": "CUST0083",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0084",
    "name": "Rahul Bansal",
    "email": "customer084@example.com",
    "password": "Demo@1083",
    "phone": "9000000084",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0084",
      "userId": "CUST0084",
      "line1": "Sector 14, Ghaziabad",
      "city": "Ghaziabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0085",
    "name": "Rohan Bansal",
    "email": "customer085@example.com",
    "password": "Demo@1084",
    "phone": "9000000085",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0085",
      "userId": "CUST0085",
      "line1": "Sector 14, East Delhi",
      "city": "East Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0086",
    "name": "Arjun Arora",
    "email": "customer086@example.com",
    "password": "Demo@1085",
    "phone": "9000000086",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0086",
      "userId": "CUST0086",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0087",
    "name": "Ananya Arora",
    "email": "customer087@example.com",
    "password": "Demo@1086",
    "phone": "9000000087",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0087",
      "userId": "CUST0087",
      "line1": "Sector 14, Bahadurgarh",
      "city": "Bahadurgarh",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0088",
    "name": "Riya Agarwal",
    "email": "customer088@example.com",
    "password": "Demo@1087",
    "phone": "9000000088",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0088",
      "userId": "CUST0088",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0089",
    "name": "Yash Gupta",
    "email": "customer089@example.com",
    "password": "Demo@1088",
    "phone": "9000000089",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0089",
      "userId": "CUST0089",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0090",
    "name": "Ishita Sethi",
    "email": "customer090@example.com",
    "password": "Demo@1089",
    "phone": "9000000090",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0090",
      "userId": "CUST0090",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0091",
    "name": "Rohan Bansal",
    "email": "customer091@example.com",
    "password": "Demo@1090",
    "phone": "9000000091",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0091",
      "userId": "CUST0091",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0092",
    "name": "Riya Mishra",
    "email": "customer092@example.com",
    "password": "Demo@1091",
    "phone": "9000000092",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0092",
      "userId": "CUST0092",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0093",
    "name": "Aarav Agarwal",
    "email": "customer093@example.com",
    "password": "Demo@1092",
    "phone": "9000000093",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0093",
      "userId": "CUST0093",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0094",
    "name": "Aanya Jain",
    "email": "customer094@example.com",
    "password": "Demo@1093",
    "phone": "9000000094",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0094",
      "userId": "CUST0094",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0095",
    "name": "Aarav Verma",
    "email": "customer095@example.com",
    "password": "Demo@1094",
    "phone": "9000000095",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0095",
      "userId": "CUST0095",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0096",
    "name": "Ishita Mishra",
    "email": "customer096@example.com",
    "password": "Demo@1095",
    "phone": "9000000096",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0096",
      "userId": "CUST0096",
      "line1": "Sector 14, East Delhi",
      "city": "East Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0097",
    "name": "Ananya Mehta",
    "email": "customer097@example.com",
    "password": "Demo@1096",
    "phone": "9000000097",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0097",
      "userId": "CUST0097",
      "line1": "Sector 14, Bahadurgarh",
      "city": "Bahadurgarh",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0098",
    "name": "Vivaan Mehta",
    "email": "customer098@example.com",
    "password": "Demo@1097",
    "phone": "9000000098",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0098",
      "userId": "CUST0098",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0099",
    "name": "Tanya Verma",
    "email": "customer099@example.com",
    "password": "Demo@1098",
    "phone": "9000000099",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0099",
      "userId": "CUST0099",
      "line1": "Sector 14, Bahadurgarh",
      "city": "Bahadurgarh",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0100",
    "name": "Aditya Chopra",
    "email": "customer100@example.com",
    "password": "Demo@1099",
    "phone": "9000000100",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0100",
      "userId": "CUST0100",
      "line1": "Sector 14, Ghaziabad",
      "city": "Ghaziabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0101",
    "name": "Kavya Arora",
    "email": "customer101@example.com",
    "password": "Demo@1100",
    "phone": "9000000101",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0101",
      "userId": "CUST0101",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0102",
    "name": "Aditya Sethi",
    "email": "customer102@example.com",
    "password": "Demo@1101",
    "phone": "9000000102",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0102",
      "userId": "CUST0102",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0103",
    "name": "Shreya Sethi",
    "email": "customer103@example.com",
    "password": "Demo@1102",
    "phone": "9000000103",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0103",
      "userId": "CUST0103",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0104",
    "name": "Kabir Gupta",
    "email": "customer104@example.com",
    "password": "Demo@1103",
    "phone": "9000000104",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0104",
      "userId": "CUST0104",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0105",
    "name": "Kavya Bansal",
    "email": "customer105@example.com",
    "password": "Demo@1104",
    "phone": "9000000105",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0105",
      "userId": "CUST0105",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0106",
    "name": "Rohan Singh",
    "email": "customer106@example.com",
    "password": "Demo@1105",
    "phone": "9000000106",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0106",
      "userId": "CUST0106",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0107",
    "name": "Riya Arora",
    "email": "customer107@example.com",
    "password": "Demo@1106",
    "phone": "9000000107",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0107",
      "userId": "CUST0107",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0108",
    "name": "Simran Malhotra",
    "email": "customer108@example.com",
    "password": "Demo@1107",
    "phone": "9000000108",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0108",
      "userId": "CUST0108",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0109",
    "name": "Yash Mishra",
    "email": "customer109@example.com",
    "password": "Demo@1108",
    "phone": "9000000109",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0109",
      "userId": "CUST0109",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0110",
    "name": "Shreya Sethi",
    "email": "customer110@example.com",
    "password": "Demo@1109",
    "phone": "9000000110",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0110",
      "userId": "CUST0110",
      "line1": "Sector 14, Faridabad",
      "city": "Faridabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0111",
    "name": "Yash Chopra",
    "email": "customer111@example.com",
    "password": "Demo@1110",
    "phone": "9000000111",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0111",
      "userId": "CUST0111",
      "line1": "Sector 14, Ghaziabad",
      "city": "Ghaziabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0112",
    "name": "Ananya Malhotra",
    "email": "customer112@example.com",
    "password": "Demo@1111",
    "phone": "9000000112",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0112",
      "userId": "CUST0112",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0113",
    "name": "Ishita Jain",
    "email": "customer113@example.com",
    "password": "Demo@1112",
    "phone": "9000000113",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0113",
      "userId": "CUST0113",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0114",
    "name": "Riya Jain",
    "email": "customer114@example.com",
    "password": "Demo@1113",
    "phone": "9000000114",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0114",
      "userId": "CUST0114",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0115",
    "name": "Arjun Mehta",
    "email": "customer115@example.com",
    "password": "Demo@1114",
    "phone": "9000000115",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0115",
      "userId": "CUST0115",
      "line1": "Sector 14, Faridabad",
      "city": "Faridabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0116",
    "name": "Kunal Verma",
    "email": "customer116@example.com",
    "password": "Demo@1115",
    "phone": "9000000116",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0116",
      "userId": "CUST0116",
      "line1": "Sector 14, Ghaziabad",
      "city": "Ghaziabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0117",
    "name": "Aanya Sharma",
    "email": "customer117@example.com",
    "password": "Demo@1116",
    "phone": "9000000117",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0117",
      "userId": "CUST0117",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0118",
    "name": "Tanya Bansal",
    "email": "customer118@example.com",
    "password": "Demo@1117",
    "phone": "9000000118",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0118",
      "userId": "CUST0118",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0119",
    "name": "Kunal Agarwal",
    "email": "customer119@example.com",
    "password": "Demo@1118",
    "phone": "9000000119",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0119",
      "userId": "CUST0119",
      "line1": "Sector 14, Gurugram",
      "city": "Gurugram",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0120",
    "name": "Kunal Sharma",
    "email": "customer120@example.com",
    "password": "Demo@1119",
    "phone": "9000000120",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0120",
      "userId": "CUST0120",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0121",
    "name": "Aditya Chopra",
    "email": "customer121@example.com",
    "password": "Demo@1120",
    "phone": "9000000121",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0121",
      "userId": "CUST0121",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0122",
    "name": "Vivaan Mehta",
    "email": "customer122@example.com",
    "password": "Demo@1121",
    "phone": "9000000122",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0122",
      "userId": "CUST0122",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0123",
    "name": "Aditya Mishra",
    "email": "customer123@example.com",
    "password": "Demo@1122",
    "phone": "9000000123",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0123",
      "userId": "CUST0123",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0124",
    "name": "Vivaan Arora",
    "email": "customer124@example.com",
    "password": "Demo@1123",
    "phone": "9000000124",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0124",
      "userId": "CUST0124",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0125",
    "name": "Aanya Verma",
    "email": "customer125@example.com",
    "password": "Demo@1124",
    "phone": "9000000125",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0125",
      "userId": "CUST0125",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0126",
    "name": "Riya Mehta",
    "email": "customer126@example.com",
    "password": "Demo@1125",
    "phone": "9000000126",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0126",
      "userId": "CUST0126",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0127",
    "name": "Rahul Khanna",
    "email": "customer127@example.com",
    "password": "Demo@1126",
    "phone": "9000000127",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0127",
      "userId": "CUST0127",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0128",
    "name": "Kavya Mehta",
    "email": "customer128@example.com",
    "password": "Demo@1127",
    "phone": "9000000128",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0128",
      "userId": "CUST0128",
      "line1": "Sector 14, Faridabad",
      "city": "Faridabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0129",
    "name": "Shreya Gupta",
    "email": "customer129@example.com",
    "password": "Demo@1128",
    "phone": "9000000129",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0129",
      "userId": "CUST0129",
      "line1": "Sector 14, Ghaziabad",
      "city": "Ghaziabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0130",
    "name": "Tanya Agarwal",
    "email": "customer130@example.com",
    "password": "Demo@1129",
    "phone": "9000000130",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0130",
      "userId": "CUST0130",
      "line1": "Sector 14, Greater Noida",
      "city": "Greater Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0131",
    "name": "Kavya Mehta",
    "email": "customer131@example.com",
    "password": "Demo@1130",
    "phone": "9000000131",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0131",
      "userId": "CUST0131",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0132",
    "name": "Kavya Sethi",
    "email": "customer132@example.com",
    "password": "Demo@1131",
    "phone": "9000000132",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0132",
      "userId": "CUST0132",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0133",
    "name": "Meera Mehta",
    "email": "customer133@example.com",
    "password": "Demo@1132",
    "phone": "9000000133",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0133",
      "userId": "CUST0133",
      "line1": "Sector 14, Ghaziabad",
      "city": "Ghaziabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0134",
    "name": "Arjun Verma",
    "email": "customer134@example.com",
    "password": "Demo@1133",
    "phone": "9000000134",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0134",
      "userId": "CUST0134",
      "line1": "Sector 14, Faridabad",
      "city": "Faridabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0135",
    "name": "Meera Kapoor",
    "email": "customer135@example.com",
    "password": "Demo@1134",
    "phone": "9000000135",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0135",
      "userId": "CUST0135",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0136",
    "name": "Meera Malhotra",
    "email": "customer136@example.com",
    "password": "Demo@1135",
    "phone": "9000000136",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0136",
      "userId": "CUST0136",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0137",
    "name": "Nisha Arora",
    "email": "customer137@example.com",
    "password": "Demo@1136",
    "phone": "9000000137",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0137",
      "userId": "CUST0137",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0138",
    "name": "Vivaan Khanna",
    "email": "customer138@example.com",
    "password": "Demo@1137",
    "phone": "9000000138",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0138",
      "userId": "CUST0138",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0139",
    "name": "Arjun Sharma",
    "email": "customer139@example.com",
    "password": "Demo@1138",
    "phone": "9000000139",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0139",
      "userId": "CUST0139",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0140",
    "name": "Diya Chopra",
    "email": "customer140@example.com",
    "password": "Demo@1139",
    "phone": "9000000140",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0140",
      "userId": "CUST0140",
      "line1": "Sector 14, New Delhi",
      "city": "New Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0141",
    "name": "Aanya Sethi",
    "email": "customer141@example.com",
    "password": "Demo@1140",
    "phone": "9000000141",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0141",
      "userId": "CUST0141",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0142",
    "name": "Arjun Mehta",
    "email": "customer142@example.com",
    "password": "Demo@1141",
    "phone": "9000000142",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0142",
      "userId": "CUST0142",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0143",
    "name": "Yash Mehta",
    "email": "customer143@example.com",
    "password": "Demo@1142",
    "phone": "9000000143",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0143",
      "userId": "CUST0143",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0144",
    "name": "Shreya Jain",
    "email": "customer144@example.com",
    "password": "Demo@1143",
    "phone": "9000000144",
    "gender": "male",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0144",
      "userId": "CUST0144",
      "line1": "Sector 14, Ghaziabad",
      "city": "Ghaziabad",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0145",
    "name": "Kabir Malhotra",
    "email": "customer145@example.com",
    "password": "Demo@1144",
    "phone": "9000000145",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0145",
      "userId": "CUST0145",
      "line1": "Sector 14, West Delhi",
      "city": "West Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0146",
    "name": "Rohan Singh",
    "email": "customer146@example.com",
    "password": "Demo@1145",
    "phone": "9000000146",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0146",
      "userId": "CUST0146",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0147",
    "name": "Nisha Mehta",
    "email": "customer147@example.com",
    "password": "Demo@1146",
    "phone": "9000000147",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0147",
      "userId": "CUST0147",
      "line1": "Sector 14, Central Delhi",
      "city": "Central Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0148",
    "name": "Aditya Jain",
    "email": "customer148@example.com",
    "password": "Demo@1147",
    "phone": "9000000148",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0148",
      "userId": "CUST0148",
      "line1": "Sector 14, Noida",
      "city": "Noida",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0149",
    "name": "Shreya Verma",
    "email": "customer149@example.com",
    "password": "Demo@1148",
    "phone": "9000000149",
    "gender": "female",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0149",
      "userId": "CUST0149",
      "line1": "Sector 14, North Delhi",
      "city": "North Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  },
  {
    "id": "CUST0150",
    "name": "Vivaan Khanna",
    "email": "customer150@example.com",
    "password": "Demo@1149",
    "phone": "9000000150",
    "gender": "other",
    "role": "customer",
    "isOnline": false,
    "rating": 5,
    "ratingCount": 1,
    "walletBalance": 0,
    "address": {
      "id": "addr_CUST0150",
      "userId": "CUST0150",
      "line1": "Sector 14, South Delhi",
      "city": "South Delhi",
      "state": "Delhi NCR",
      "pincode": "110001",
      "isDefault": true
    },
    "createdAt": "2026-08-08"
  }

];

// Clean Production State - 0 dummy sample clothes
export const initialItems: Item[] = [];

export const initialOffers: Offer[] = [];

// Clean initial requests & batches
export const initialPickups: PickupRequest[] = [];

export const initialBatches: RecyclingBatch[] = [];

export const initialOrders: Order[] = [];

export const initialAnalytics: AnalyticsData = {
  pilotStage: 'Delhi NCR Startup Operating System',
  totalUsers: 153,
  activeListingsCount: 0,
  delhiNcrPartners: 4,
  pendingPickupRequests: 0,
  pendingIndustryVerifications: 0,
  tier1ApprovedCount: 0,
  tier2RecyclingWeightKg: 0
};
